### ISSUE TITLE
ox generate migration - panics if no args provided

### ISSUE THREAD

**Issue by dannov91** [wawandco/oxplugins#23]
Hey guys! Love how migration command is going so far. Used it and tastes sweet!
Some minor things:

1. I ran `ox generate migration` hoping to find docs about how it works, instead I got
`panic: runtime error: index out of range [2] with length 2`

2. Related to the above, running `ox generate migration -h` created a migration file in ./migrations folder instead.

3. Do you think the default folder where the file is generated should be the current working directory where the command is executed, instead of taking ./migrations? (just taking the reference from how buffalo liquibase works)

LMK any questions!

**Comment by paganotoni** [comment]
Thanks for this one Danny! We will go for it soon.
